name: tox

on:
  pull_request:
    branches:
      - main

jobs:
  tox:
    name: tox linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install deps
        run: python -m pip install tox

      - name: Run tox test
        run: python -m tox
